# | Auto Start |
# autostart your favorite applications here

exec-once = noctalia &
exec-once = /opt/freedownloadmanager/fdm --hidden &
exec-once = pass-cli ssh-agent daemon start &
exec-once = steam -silent &
exec-once = /opt/windscribe/Windscribe --autostart &
exec-once = /usr/bin/cachyos-hello &
