# | Input Devices |
# Configure your input devices here. | https://mangowm.github.io/docs/configuration/input

# Keyboard settings
xkb_rules_layout = us,tr
xkb_rules_options = grp:alt_shift_toggle
numlockon = 1
repeat_rate = 40
repeat_delay = 250

# Mouse settings
# If you want to disable pointer acceleration, uncomment the lines below.
mouse_accel_profile = 1
mouse_accel_speed = -0.6

# Touchpad / Trackpad settings
trackpad_natural_scrolling = 1
tap_to_click = 1
tap_and_drag = 1

# Cursor behavior
cursor_hide_timeout = 5
warpcursor = 1
