# | Miscellaneous |
# https://mangowm.github.io/docs/configuration/miscellaneous

allow_tearing = 2
syncobj_enable = 1
# xwayland-persistence = 1

drag_tile_to_tile = 1

# Hotarea (0 = Top-left, 1 = Top-right, 2 = Bottom-left, 3 = Bottom-right)
enable_hotarea = 1
hotarea_size = 10
hotarea_corner = 0
