# | Rules |
# Window/Tag/Layer rules. | https://mangowm.github.io/docs/window-management/rules

# Unfocused windows transparency / dimming (0.80 = %80 opacity)
windowrule = unfocused_opacity:0.80, appid:.*

# Workspace Assignments
windowrule = tags:1, appid:(?i)vivaldi.*
windowrule = tags:3, appid:(?i)obsidian.*
windowrule = tags:4, appid:(?i)steam.*
windowrule = tags:5, appid:(?i).*jellyfin.*
windowrule = tags:5, title:(?i).*jellyfin.*
windowrule = tags:5, appid:(?i).*fladder.*
windowrule = tags:5, title:(?i).*fladder.*

# Steam Rules
windowrule = isfloating:1, appid:(?i)steam.*
windowrule = isfloating:0, appid:(?i)steam.*, title:^Steam$
windowrule = isfloating:1, appid:(?i)steam.*, title:(?i).*notificationtoasts.*

# Proton Pass Named Scratchpad
windowrule = isnamedscratchpad:1, appid:(?i)proton.*
windowrule = isnamedscratchpad:1, title:(?i)proton.*

# Floating Windows
windowrule = isfloating:1, appid:(?i)windscribe.*
windowrule = isfloating:1, appid:(?i).*cachyos-hello.*
windowrule = isfloating:1, title:(?i)cachyos.*hello.*
windowrule = isfloating:1, appid:(?i)kcalc.*
windowrule = isfloating:1, appid:(?i)zenity.*
windowrule = isfloating:1, title:(?i).*ekran kaydı.*
windowrule = isfloating:1, appid:(?i).*screenchooser.*
windowrule = isfloating:1, title:(?i).*ekran paylaşımı.*
windowrule = isfloating:1, appid:(?i)scrcpy.*
windowrule = isfloating:1, title:(?i).*scrcpy.*

layerrule = noanim:1, noblur:1, layer_name:selection


