# | Rules |
# Window/Tag/Layer rules. | https://mangowm.github.io/docs/window-management/rules

# Unfocused windows transparency / dimming (0.80 = %80 opacity)
windowrule = unfocused_opacity:0.80, appid:.*

windowrule = isfloating:1, appid:[Ss]team
windowrule = isfloating:0, title:Steam
windowrule = isfloating:1, appid:steam, title:Steam Settings

# Proton Pass Named Scratchpad
windowrule = isnamedscratchpad:1, appid:proton-pass
windowrule = isnamedscratchpad:1, title:Proton Pass

layerrule = noanim:1, noblur:1, layer_name:selection
