# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x101415ff
bordercolor = 0x889395ff
dropcolor = 0x7dd3e380
splitcolor = 0xe2b7f8ff
focuscolor = 0x7dd3e3ff
maximizescreencolor = 0xacccd3ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe2b7f8ff
globalcolor = 0x429dacff
overlaycolor = 0x2f4e53ff
jump_label_decorate_fg_color = 0xe0e3e4ff
jump_label_decorate_bg_color = 0x262b2cff
jump_label_decorate_focus_fg_color = 0x00363eff
jump_label_decorate_focus_bg_color = 0x7dd3e3ff
jump_label_decorate_border_color = 0x889395ff
group_bar_decorate_fg_color = 0xe0e3e4ff
group_bar_decorate_bg_color = 0x262b2cff
group_bar_decorate_focus_fg_color = 0x00363eff
group_bar_decorate_focus_bg_color = 0x7dd3e3ff
group_bar_decorate_border_color = 0x889395ff
