# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x000000ff
rootcolor = 0x121415ff
bordercolor = 0x8c9197ff
dropcolor = 0xaacae580
splitcolor = 0xdabde3ff
focuscolor = 0xaacae5ff
maximizescreencolor = 0xbcc8d3ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xdabde3ff
globalcolor = 0x103348ff
overlaycolor = 0x3d4852ff
jump_label_decorate_fg_color = 0xe3e2e4ff
jump_label_decorate_bg_color = 0x292a2cff
jump_label_decorate_focus_fg_color = 0x113348ff
jump_label_decorate_focus_bg_color = 0xaacae5ff
jump_label_decorate_border_color = 0x8c9197ff
group_bar_decorate_fg_color = 0xe3e2e4ff
group_bar_decorate_bg_color = 0x292a2cff
group_bar_decorate_focus_fg_color = 0x113348ff
group_bar_decorate_focus_bg_color = 0xaacae5ff
group_bar_decorate_border_color = 0x8c9197ff
